name: Build-Artifacts

on:
  push:
    branches:
      - main

jobs:
  create-artifact:
    name: Build and Create Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run create appimage script
        run: ./create_appimage.sh

      - uses: actions/upload-artifact@v4
        with:
          name: Editlite.AppImage
          path: Editlite-x86_64.AppImage
